version : '3'

services:
  db: 
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: donation
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"  
  web:
    build : .
    command : python donation/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db  