# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 12:21
from __future__ import unicode_literals

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='category',
            name='descriptions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=category.models.uplaod_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
