# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20170806_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
