# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-29 07:40
from __future__ import unicode_literals

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20171102_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=category.models.uplaod_location, width_field=b'width_field'),
        ),
    ]
