# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-04 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='resized_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
