# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 13:24
from __future__ import unicode_literals

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20180206_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, height_field=b'height_field', max_length=500, null=True, upload_to=category.models.uplaod_location_test, width_field=b'width_field'),
        ),
        migrations.AlterField(
            model_name='category',
            name='resized_image',
            field=models.ImageField(blank=True, height_field=b'height_field', max_length=500, null=True, upload_to=category.models.uplaod_location_test, width_field=b'width_field'),
        ),
    ]
