# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_auto_20180207_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
