# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_category_cover_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
