# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170821_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='provider_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'user/'),
        ),
    ]
