# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-08 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[(b'A+', b'A POSITIVE'), (b'A-', b'A NEGATIVE'), (b'B+', b'B POSITIVE'), (b'B-', b'B NEGATIVE'), (b'O+', b'O POSITIVE'), (b'O-', b'O NEGATIVE'), (b'AB+', b'AB POSITIVE'), (b'AB-', b'AB NEGATIVE')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='covid_recover_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_blood_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_plasma_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_mobile_number',
            field=models.BooleanField(default=False),
        ),
    ]
