# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-22 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'newsletter_subscribers',
            },
        ),
    ]
